version: "3"
services:
  ugram:
    build: ugram
    ports:
      - "3000:3000"
    volumes:
      - ./ugram/src:/app/src
    depends_on:
      - ugrambackend

  ugrambackend:
    build: ugramBackend
    ports:
      - "8080:8080"
    volumes:
      - ./ugramBackend/src:/server/src
    depends_on:
      - mysql

  mysql:
    image: "mysql:8.0"
    environment:
      - MYSQL_ROOT_PASSWORD=equipe5
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:ro
    ports:
      - "8000:3306"
    expose:
      - 8000
